"""add labs and lifestyle assessments

Revision ID: 5a7bb0a042f9
Revises: fcd00529f014
Create Date: 2026-09-18 10:59:40.573949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7bb0a042f9'
down_revision = 'fcd00529f014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_profile_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('reference_text', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['health_profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifestyle_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_profile_id', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('fruit_vegetable_servings', sa.Float(), nullable=True),
    sa.Column('processed_food_frequency', sa.String(length=50), nullable=True),
    sa.Column('dietary_pattern', sa.String(length=100), nullable=True),
    sa.Column('water_cups_per_day', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('sleep_schedule_consistent', sa.Boolean(), nullable=True),
    sa.Column('exercise_days_per_week', sa.Integer(), nullable=True),
    sa.Column('exercise_minutes_per_session', sa.Integer(), nullable=True),
    sa.Column('sedentary_hours_per_day', sa.Float(), nullable=True),
    sa.Column('movement_notes', sa.Text(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('primary_stressors', sa.Text(), nullable=True),
    sa.Column('relaxation_practice', sa.String(length=255), nullable=True),
    sa.Column('outdoor_days_per_week', sa.Integer(), nullable=True),
    sa.Column('outdoor_minutes_average', sa.Integer(), nullable=True),
    sa.Column('environment_notes', sa.Text(), nullable=True),
    sa.Column('current_herbs_teas', sa.Text(), nullable=True),
    sa.Column('current_supplements', sa.Text(), nullable=True),
    sa.Column('natural_health_goals', sa.Text(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('personal_goals', sa.Text(), nullable=True),
    sa.Column('barriers', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['health_profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifestyle_assessments')
    op.drop_table('lab_results')
    # ### end Alembic commands ###
