"""expand wellness resource discovery

Revision ID: f24b4b267600
Revises: eb97829a902a
Create Date: 2026-09-18 15:05:04.881723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24b4b267600'
down_revision = 'eb97829a902a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultural_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dietary_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('services', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resource_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('appointment_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_resources', schema=None) as batch_op:
        batch_op.drop_column('source_url')
        batch_op.drop_column('appointment_required')
        batch_op.drop_column('languages')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('services')
        batch_op.drop_column('dietary_tags')
        batch_op.drop_column('cultural_tags')

    # ### end Alembic commands ###
